service: emtoion

provider:
  name: aws
  runtime: nodejs12.x

custom:
  customDomain:
    domainName: api.gamstagram.com
    certificateName: '*.gamstagram.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
  warmup:      
      - production
      - staging

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-domain-manager

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - node_modules 
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
