service: emtoion

provider:
  name: aws
  memorySize: 512
  region: ap-northeast-2
  runtime: nodejs12.x

custom:
  customDomain:
    domainName: api.gamstagram.com
    certificateName: '*.gamstagram.com'
    createRoute53Record: true
    endpointType: 'regional'
    apiType: rest
  warmup:      
    enabled: true
    folderName: '_warmup'
    cleanFolder: false
    memorySize: 256
    name: 'make-them-pop'

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-domain-manager

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - node_modules 
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
