version: 2.1
orbs:
  node: circleci/node@1.1.6
  coveralls: coveralls/coveralls@x.y.z
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install && make test-coverage
            - coveralls/upload
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
