name: Deploy Prod
on:
  push:
    branches:
      - master
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_EMOTION_IAM_ACCESS_KEY }} --secret ${{ secrets.AWS_EMOTION_IAM_SECRET_KEY }}
    - name: Create env file
      run: | # cp sample.env.yml env.yml
        cat > env.yml << EOF
        ${{ secrets.ENV }}
        EOF
    - name: Install NPM dependencies
      run: npm install
    - name: Build assets
      run: npm run build
    - name: Deploy Lambda functions
      run: sls deploy -s prod
    # Optional (to use with serverless-finch serverless plugin)
    #- name: Deploy assets to S3
    #  run: sls client deploy --no-delete-contents --no-confirm -s prod
