on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Showing dir
      run: ls -al
    - name: Generate .env file
      run: node provide.env.js 
      env: 
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
        SLACK_WEBHOOK_URL_OF_NEW: ${{ secrets.SLACK_WEBHOOK_URL_OF_NEW }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        APP_AWS_ACCESS_KEY_ID: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
        APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
        TINYPNG_API_KEY: ${{ secrets.TINYPNG_API_KEY }}
        AWS_S3_IMAGE_UPLOAD_BUCKET: ${{ secrets.AWS_S3_IMAGE_UPLOAD_BUCKET }}
        STATIC_IMAGE_HOST: ${{ secrets.STATIC_IMAGE_HOST }}
    - name: Showing dir
      run: ls -al
    - name: npm install
      run: npm install 
    - name: Build
      run: npm run build
    - name: serverless deploy
      uses: serverless/github-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EMOTION_IAM_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EMOTION_IAM_SECRET_KEY }}
      with:
        args: deploy
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      if: always() # Pick up events even if the job fails or is canceled.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
