on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Showing dir
      run: ls -al
    - name: Npm install
      run: npm install 
    - name: Build
      run: npm run build
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      if: always() # Pick up events even if the job fails or is canceled.
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.AWS_EMOTION_IAM_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

        # or if using AWS creds directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
